DiChoSaiGon/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DiChoSaiGon.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using DiChoSaiGon.Helpper;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace DiChoSaiGon.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize]
    public class AdminProductsController : Controller
    {
        private readonly NorthwindContext _context;
        public INotyfService _notyfService { get; }
        public AdminProductsController(NorthwindContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminProducts
        public IActionResult Index(int page = 1, int CatID = 0)
        {
            var pageNumber = page;
            var pageSize = 20;

            List<Product> lsProducts = new List<Product>();

            if (CatID != 0)
            {
                lsProducts = _context.Products
                    .AsNoTracking()
                    .Where(x => x.CategoryId == CatID)
                    .Include(x => x.Category)
                    .OrderByDescending(x => x.ProductId).ToList();
            }
            else
            {
                lsProducts = _context.Products
                    .AsNoTracking()
                    .Include(x => x.Category)
                    .OrderByDescending(p => p.ProductId).ToList();
            }

            PagedList<Product> models = new PagedList<Product>(lsProducts.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentCatID = CatID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            return View(models);
        }

        public IActionResult Filter(int CatID = 0)
        {
            var url = $"/Admin/AdminProducts?CatID={CatID}";
            if (CatID == 0)
            {
                url = $"/Admin/AdminProducts";
            }
            return Json(new { status = "success", rediectUrl = url });
        }
        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");            
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,SupplierId,CategoryId,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,Discount,Video,Alias,Picture,MetaKey,BestSellers,HomeFlag,Active,Tags,Title,MetaDesc")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                product.ProductName = Utilities.ToTitleCase(product.ProductName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(product.ProductName) + extension;
                    product.Picture = await Utilities.UploadFile(fThumb, @"product", image.ToLower());
                }
                if (string.IsNullOrEmpty(product.Picture)) product.Picture = "default.jpg";
                product.Alias = Utilities.SEOUrl(product.ProductName);
                
                _context.Add(product);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm sản phẩm thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,SupplierId,CategoryId,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,Discount,Video,Alias,Picture,MetaKey,BestSellers,HomeFlag,Active,Tags,Title,MetaDesc")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ProductName = Utilities.ToTitleCase(product.ProductName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(product.ProductName) + extension;
                        product.Picture = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(product.Picture)) product.Picture = "default.jpg";
                    _context.Update(product);
                    _notyfService.Success("Cập nhật thành công");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            
            return View(product);
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Supplier)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

DiChoSaiGon/Areas/Admin/Views/AdminProducts/Create.cshtml
@model DiChoSaiGon.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
                <div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                    <img src="assets/images/others/thumb-16.jpg" alt="">
                </div>
                <div class="m-l-15">
                    <h4 class="m-b-0">Skinny Men Blazer</h4>
                    <p class="text-muted m-b-0">Code: #5325</p>
                </div>
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Save</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Basic Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Option Info</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Description</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên sản phẩm</label>
                        <input type="text" class="form-control" asp-for="ProductName">
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Giá bán</label>
                            <input type="text" class="form-control" asp-for="UnitPrice">
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Discount</label>
                            <input type="text" class="form-control" asp-for="Discount">
                        </div>
                    </div>
                    <div>
                        <div class="form-group">
                            <label class="font-weight-semibold" for="productCategory">Danh mục sản phẩm</label>
                            <select class="custom-select" asp-for="CategoryId" style="min-width: 200px;" asp-items="ViewBag.DanhMuc">
                                <option selected>Chọn danh mục</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Còn trong kho</label>
                            <input type="text" class="form-control" asp-for="UnitsInStock">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Picture" />
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    @*<div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="Discontinued" /> @Html.DisplayNameFor(model => model.Discontinued)
                            </label>
                        </div>*@
                    <div class="row">
                        <div class="form-group d-flex align-items-center col-md-3">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="Discontinued">
                                <label for="Discontinued"></label>
                            </div>
                            <label>@Html.DisplayNameFor(model => model.Discontinued)</label>
                        </div>
                        <div class="form-group d-flex align-items-center col-md-3">
                            <div class="switch m-r-10 check-box">
                                <input type="checkbox" asp-for="Active" checked="">
                                <label for="Active"></label>
                            </div>
                            <label>Public</label>
                        </div>
                        <div class="form-group d-flex align-items-center col-md-3">
                            <div class="switch m-r-10 check-box">
                                <input type="checkbox" asp-for="HomeFlag">
                                <label for="HomeFlag"></label>
                            </div>
                            <label>Out of Stock</label>
                        </div>
                        @*id="switch-3" name="switch-3" @((Model.BestSellers == false ? "" : "checked"))*@
                        <div class="form-group d-flex align-items-center col-md-3">
                            <div class="switch m-r-10 check-box">
                                <input type="checkbox" asp-for="BestSellers">
                                <label for="BestSellers"></label>
                            </div>
                            <label>Pending</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">Tags</label>
                        <input type="text" class="form-control" asp-for="Tags">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Description"></textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <a asp-action="Index" class="btn btn-primary">Back to List</a>
        </div>
    </div>
</form>

DiChoSaiGon/Areas/Admin/Views/AdminProducts/Delete.cshtml
@model DiChoSaiGon.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityPerUnit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityPerUnit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsOnOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsOnOrder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReorderLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReorderLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discontinued)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discontinued)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestSellers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestSellers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomeFlag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomeFlag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supplier.CompanyName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DiChoSaiGon/Areas/Admin/Views/AdminProducts/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<DiChoSaiGon.Models.Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Danh sách sản phẩm: page @ViewBag.CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="col-md-5">
                        <div class="input-affix m-v-10">
                            <i class="prefix-icon anticon anticon-search opacity-04"></i>
                            <input id="keyword" type="text" class="form-control" placeholder="Tìm kiếm sản phẩm">
                        </div>
                    </div>
                    <div class="input-affix m-v-10">
                        <select class="custom-select" id="catID" name="catID" style="min-width: 150px;" asp-items="ViewBag.DanhMuc">
                            <option selected>Chọn danh mục</option>
                            <option value="0">Chọn tất cả</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminProducts" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Add Product</span>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên sản phẩm</th>
                        <th>Số lượng mỗi đơn vị</th>
                        <th>Đơn giá</th>
                        <th>Tồn kho</th>
                        <th>Đã đặt</th>
                        <th>Danh mục</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="records_table">
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ProductId</td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img class="img-fluid rounded" src="assets/images/others/thumb-9.jpg" style="max-width: 60px" alt="">
                                        <h6 class="m-b-0 m-l-10">@item.ProductName</h6>
                                    </div>
                                </td>
                                <td>@item.UnitsInStock</td>
                                <td>@item.UnitPrice</td>

                                <td>
                                    @if (item.UnitsInStock > 0)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>In Stock</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Out Stock</div>
                                        </div>
                                    }
                                </td>
                                <td>@item.UnitsOnOrder</td>
                                <td>@item.Category.CategoryName</td>
                                <td class="text-right">
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminProducts" asp-action="Details" asp-route-id="@item.ProductId">View</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminProducts" asp-action="Edit" asp-route-id="@item.ProductId">Edit</a>
                                    <a class="btn btn-danger btn-tone m-r-5" asp-area="Admin" asp-controller="AdminProducts" asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        import { type } from "jquery";

        $(document).ready(function () {
            jQuery("#txtCatID").change(function () {
                var catID = jQuery(this).children(":selected").attr("value");
                catID = parseFloat(catID);
                $('#txtCatID option')
                    .remove('selected');
                $("#txtCatID > [value=" + catID + "]").attr("selected", "true");
                $.ajax({
                    url: '/Admin/AdminProducts/Filter',
                    datatype: "json",
                    type: "GET",
                    data: {
                        CategoryID: catID
                    },
                    async: true,
                    success: function (results) {
                        if (results.status == "success") {
                            window.location.href = results.redirectUrl;
                        }
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
            });
        });

        $("#keyword").keyup(function () {
            var strkeyword = $('#keyword').val();
            $.ajax({
                url: '/Admin/Search/FindProduct/',
                datatype: "json",
                type: "POST",
                data: { keyword: strkeyword },
                async: true,
                success: function (results) {
                    $("#records_table").html("");
                    $("#records_table").html(results);
                },
                error: function (xhr) {
                    alert('error');
                }
            })
        })
    </script>
}