DiChoSaiGon/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DiChoSaiGon.Models;
using DiChoSaiGon.Helpper;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using System.IO;

namespace DiChoSaiGon.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly NorthwindContext _context;
        public INotyfService _notyfService { get; }
        public AdminCategoriesController(NorthwindContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsCategorys = _context.Categories
                .AsNoTracking()
                .OrderBy(x => x.CategoryId);
            PagedList<Category> models = new PagedList<Category>(lsCategorys, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName,Description,ParentId,Levels,Ordering,Published,Alias,Picture,Title,MetaKey,MetaDesc,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(category.CategoryName) + extension;
                    category.Picture = await Utilities.UploadFile(fThumb, @"category", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(category.Picture)) 
                {
                    category.Picture = "default.jpg";
                }
                category.Alias = Utilities.SEOUrl(category.CategoryName);

                _context.Add(category);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName,Description,ParentId,Levels,Ordering,Published,Alias,Picture,Title,MetaKey,MetaDesc,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(category.CategoryName) + extension;
                        category.Picture = await Utilities.UploadFile(fThumb, @"category", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(category.Picture))
                    {
                        category.Picture = "default.jpg";
                    }
                    category.Alias = Utilities.SEOUrl(category.CategoryName);
                    
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Chỉnh sửa thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

DiChoSaiGon/Areas/Admin/Views/AdminCategories/Create.cshtml
@model DiChoSaiGon.Models.Category

@{
    ViewData["Title"] = "Tạo mới danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Tạo mới danh mục sản phẩm</a>
            <span class="breadcrumb-item active">Tạo mới danh mục</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-plus-circle"></i>
                    <span>Tạo mới danh mục</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên danh mục</label>
                        <input type="text" class="form-control" asp-for="CategoryName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Picture" />
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="Published" type="checkbox" />
                                <label for="Published">Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Description"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

DiChoSaiGon/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model DiChoSaiGon.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Levels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Levels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cover)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cover)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SchemaMarkup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SchemaMarkup)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DiChoSaiGon/Areas/Admin/Views/AdminCategories/Details.cshtml
@model DiChoSaiGon.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh sách Page</a>
            <span class="breadcrumb-item active">Danh mục : @Model.CategoryName</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/category/@Model.Picture" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.CategoryName</h4>
                <p class="text-muted m-b-0">ID: #@Model.CategoryId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CategoryId">Sửa đổi</a>
        </div>
    </div>
</div>
<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ParentId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Levels)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Levels)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Published)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Published)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cover)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cover)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SchemaMarkup)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SchemaMarkup)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CategoryId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DiChoSaiGon/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model DiChoSaiGon.Models.Category

@{
    ViewData["Title"] = "Chỉnh sửa danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Tạo mới danh mục sản phẩm</a>
            <span class="breadcrumb-item active">Sửa danh mục: @Model.CategoryName</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CategoryId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CategoryId" />
    <input type="hidden" asp-for="Picture" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu danh mục</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên danh mục</label>
                        <input type="text" class="form-control" asp-for="CategoryName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Picture" />
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group d-flex align-items-center">
                            <div class="checkbox">
                                <input asp-for="Published" type="checkbox" />
                                <label for="Published">Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Description"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

DiChoSaiGon/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<DiChoSaiGon.Models.Category>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách sản phẩm " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Danh sách Page : trang @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm danh mục</span></a>
            </div>
            <div class="col-lg-4 text-right">

            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên danh mục</th>
                        <th>Sắp xếp</th>
                        <th>Trạng thái</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            string url = $"/{item.Alias}";
                            <tr>
                                <td>@item.CategoryId</td>
                                <td>
                                    <a target="_blank" href="@url">@item.CategoryName</a>
                                </td>
                                <td>@item.Ordering</td>
                                <td>
                                    @if (item.Published == true)
                                    {


                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div> }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Non-Public</div>
                                        </div>}


                                </td>

                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.CategoryId">Chi tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.CategoryId">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.CategoryId">Xóa</a>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>